version: 2
jobs:
  one:
    docker:
      - image: circleci/python:3.6.1
    environment:
        FLASK_CONFIG: testingNew 
    working_directory: ~/temp
    steps:
      - checkout
      - run: echo ${FLASK_CONFIG}
      - run: echo "Install requirements"
      - run:  
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install awscli
            aws --version
      - run: echo done
workflows:
  version: 2
  Project:
    jobs:
      - one
