version: 2
jobs:
  one:
    docker:
      - image: circleci/python:3.6.1
    environment:
        FLASK_CONFIG: testingNew 
    steps:
      - checkout
      - run: echo ${FLASK_CONFIG}
      - run: echo "Install requirements"
      - run:  
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run: echo done    
      - run:
          name: push to aws
          command: |
            . venv/bin/activate
            aws deploy push --application-name MPC-test --description "This is a revision for the application MPC-test" --ignore-hidden-files --s3-location s3://ohi-inspire-codedeploy/test.zip --source .
workflows:
  version: 2
  Project:
    jobs:
      - one
