version: 2
jobs:
  one:
    docker:
      - image: circleci/python:3.6.1
    environment:
        FLASK_CONFIG: testingNew
    working_directory: /tmp
    steps:
      - checkout
      - run: echo ${FLASK_CONFIG}
      - run: echo "Install requirements"
      - run:  
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run: echo done 
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;

      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file

      - store_artifacts:
          path: /tmp/artifacts
workflows:
  version: 2
  Project:
    jobs:
      - one
